---
- name: Very Low Quality Ansible Playbook
  hosts: all
  become: true
  vars:
    db_password: mysecretpassword
  tasks:
    - name: Include non-existent tasks
      ansible.builtin.include_tasks: nonexistent_tasks.yml

    - name: Install httpd using command (non-idempotent)
      ansible.builtin.command: yum install -y httpd

    - name: Install non_existent_package
      ansible.builtin.yum:
        name: non_existent_package
        state: present

    - name: Remove httpd
      ansible.builtin.yum:
        name: httpd
        state: absent

    - name: Start httpd service (which is removed)
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create directory using shell
      ansible.builtin.shell: mkdir /tmp/newdir

    - name: Copy a file that doesn't exist
      ansible.builtin.copy:
        src: /path/to/nonexistent/file
        dest: /dest/path

    - name: Use undefined variable
      ignore_errors: true
      ansible.builtin.debug:
        msg: "{{ undefined_variable }}"

    - name: Create file with password
      ansible.builtin.copy:
        content: "password: {{ db_password }}"
        dest: /tmp/password.txt

    - name: Add line to non-existent file
      ansible.builtin.lineinfile:
        path: /tmp/nonexistent.conf
        line: some_line
        create: false

    - name: Clone git repo with invalid URL
      ansible.builtin.git:
        repo: invalid_url
        dest: /tmp/repo

    - name: Use raw module
      ansible.builtin.raw: echo "Hello" > /tmp/hello.txt

- name: Play without become
  hosts: all
  become: false
  tasks:
    - name: Try to install package without become
      ansible.builtin.yum:
        name: httpd
        state: present

- name: Play with undefined host
  hosts: specific_host
  tasks:
    - name: Run a failing command
      ansible.builtin.shell: this_command_does_not_exist
