- name: Very Low Quality Ansible Playbook
  hosts: all
  become: yes
  vars:
    db_password: mysecretpassword
  tasks:
    - name: Include non-existent tasks
      include_tasks: nonexistent_tasks.yml
    - name: Install httpd using command (non-idempotent)
      command: yum install -y httpd
    - name: Install non_existent_package
      yum:
        name: non_existent_package
        state: present
    - name: Remove httpd
      yum:
        name: httpd
        state: absent
    - name: Start httpd service (which is removed)
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Create directory using shell
      shell: mkdir /tmp/newdir
    - name: Copy a file that doesn't exist
      copy:
        src: /path/to/nonexistent/file
        dest: /dest/path
    - name: Use undefined variable
      debug:
        msg: "{{ undefined_variable }}"
      ignore_errors: yes
    - name: Create file with password
      copy:
        content: "password: {{ db_password }}"
        dest: /tmp/password.txt
    - name: Add line to non-existent file
      lineinfile:
        path: /tmp/nonexistent.conf
        line: "some_line"
        create: no
    - name: Clone git repo with invalid URL
      git:
        repo: invalid_url
        dest: /tmp/repo
    - name: Use raw module
      raw: echo "Hello" > /tmp/hello.txt

- name: Play without become
  hosts: all
  become: no
  tasks:
    - name: Try to install package without become
      yum:
        name: httpd
        state: present

- name: Play with undefined host
  hosts: specific_host
  tasks:
    - name: Run a failing command
      shell: this_command_does_not_exist
